import { createApp } from "vue";
import App from "./App.vue";
import store from "./store";
import router from "./router";
import "./assets/css/nucleo-icons.css";
import "./assets/css/nucleo-svg.css";
import VueSweetalert2 from "vue-sweetalert2";
import MaterialDashboard from "./material-dashboard";
import * as apolloProvider from "./apollo.provider";
import "./assets/css/style.css";
import VueDatePicker from "@vuepic/vue-datepicker";
import "@/assets/css/datepicker.css";

const appInstance = createApp(App);
appInstance.use(apolloProvider.provider);
appInstance.use(store);
appInstance.use(router);
appInstance.use(VueSweetalert2);
appInstance.use(MaterialDashboard);
appInstance.component("VueDatePicker", VueDatePicker);
appInstance.mount("#app");
